# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            'to shreds, you say?' 
tagline:          ''
description:      'Made by <a href="https://twitter.com/speed_rs" target="_blank">@speedRS</a>.'
url:              http://blog.toshredsyousay.com
baseurl:          /

author:
name:           'Richard Speter'
url:            https://twitter.com/speed_rs
version: 1.0.0